name: datasci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - country_converter
  - pandas
  - altair
  - vl-convert-python
  - beautifulsoup4
  - boto3
  - requests
  - selenium
  - geopandas
  - ipykernel
  - notebook
  - openai
  - scikit-learn
  - scikit-optimize
  - scipy
  - seaborn
  - pip